### ISSUE TITLE
Possible to write to file 

### ISSUE THREAD

**Issue by Tjoosten** [nunomaduro/phpinsights#83] opened 2019-05-17 08:51 UTC
Hi first of all thanks for the great package. 

But i'm worndering is there is a possibility to write the output to a file. Because for me personally is it messy to view the output on the terminal.

**Comment by akosglue** [comment] 2019-05-17 08:59
I think it will be handled within https://github.com/nunomaduro/phpinsights/issues/61

**Comment by nunomaduro** [comment] 2019-05-17 11:07
Duplicate of https://github.com/nunomaduro/phpinsights/issues/61.

**Closed by nunomaduro** 2019-05-17 11:07 UTC
