### ISSUE TITLE
Method does not need documentation comment should ignore `phpmd SuppressWarnings`

### ISSUE THREAD

**Issue by Gummibeer** [nunomaduro/phpinsights#260] opened 2019-08-28 14:11 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| Library version  | v1.9.0

> • **[Code] Type hint declaration:**
>  `app/Providers/AzureStorageServiceProvider.php:16`: Method `\App\Providers\AzureStorageServiceProvider::boot()` does not need documentation comment.

And this is the actual code:
```php
/** @SuppressWarnings(PHPMD.UnusedLocalVariable) */
public function boot(): void
```

I believe that this tool should ignore comments needed for other tools.

**Comment by olivernybroe** [comment] 2019-08-29 07:04
You can set `allAnnotationsAreUseful` to true in the configuration of that insight.

**Comment by Gummibeer** [comment] 2019-08-29 07:45
@olivernybroe which helps for the moment but isn't the exact same. Because now also this passes:

```php
/**
 * @param string $value
 *
 * @return string
 */
public function lower(string $value): string 
{
}
```

But thanks, it still helps me to get around these issues. :)

**Comment by olivernybroe** [comment] 2019-08-29 07:52
@Gummibeer Yeah, the problem is that this is a limitation in the sniff we are using. 
So we either have to create our own sniff to do this or a PR and hope they will accept it at the package which owns the sniff.

**Comment by JustSteveKing** [comment] 2022-03-08 11:52
No movement for years, closing to reassess at a later date if this becomes an issue again

**Closed by JustSteveKing** 2022-03-08 11:52 UTC
Labels: bug
