### ISSUE TITLE
Argument 1 passed to NunoMaduro\PhpInsights\Domain\DetailsComparator::__invoke() must be an instance of NunoMaduro\PhpInsights\Domain\Details, string given

### ISSUE THREAD

**Issue by hwmatthewa** [nunomaduro/phpinsights#379] opened 2020-03-12 19:20 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.14.0

The exception in the title was thrown while running the following command:
`
/home/HWLibs/Classes/vendor/nunomaduro/phpinsights/bin/phpinsights analyse --config-path=/home/.ci/phpinsights.php /home/HWLibs/Classes | tee phpinsights.txt
`

The exception is thrown during the code issues portion of the script

Here's the stack trace:
```
Fatal error: Uncaught TypeError: Argument 1 passed to NunoMaduro\PhpInsights\Domain\DetailsComparator::__invoke() must be an instance of NunoMaduro\PhpInsights\Domain\Details, string given in /home/HWLibs/Classes/vendor/nunomaduro/phpinsights/src/Domain/DetailsComparator.php:12
 Stack trace:
 #0 [internal function]: NunoMaduro\PhpInsights\Domain\DetailsComparator->__invoke('/home/HWLibs/Cl...', '/home/HWLibs/Cl...')
 #1 /home/HWLibs/Classes/vendor/nunomaduro/phpinsights/src/Application/Console/Formatters/Console.php(323): usort(Array, Object(NunoMaduro\PhpInsights\Domain\DetailsComparator))
 #2 /home/HWLibs/Classes/vendor/nunomaduro/phpinsights/src/Application/Console/Formatters/Console.php(97): NunoMaduro\PhpInsights\Application\Console\Formatters\Console->issues(Object(NunoMaduro\PhpInsights\Domain\Insights\InsightCollection), Array, '/home/HWLibs/Cl...')
 #3 /home/HWLibs/Classes/vendor/nunomaduro/phpinsights/src/Application/Console/Formatters/Multiple.php(27): NunoMaduro\PhpInsights\Application\Console\Formatters\Console->f in /home/HWLibs/Classes/vendor/nunomaduro/phpinsights/src/Domain/DetailsComparator.php on line 12
```

**Comment by olivernybroe** [comment] 2020-03-13 09:49
I was not able to reproduce it based on the following information. 
Could you share instructions on how to reproduce, it might be something with some specific code in a file.

**Comment by olivernybroe** [comment] 2020-03-16 09:18
Closing because not reproducible, when more info is given, we can re-open.

**Closed by olivernybroe** 2020-03-16 09:18 UTC
Labels: question
