### ISSUE TITLE
Dependencies hell: conflicts not easy to solve

### ISSUE THREAD

**Issue by Aerendir** [nunomaduro/phpinsights#343] opened 2020-01-17 09:53 UTC
I'm trying to install PHPInsights in my project, but it is not possible due to some conflicts on `phpstan/phpdoc-parser`.

This is the log:

```console
Problem 1
    - Conclusion: don't install nunomaduro/phpinsights v1.11.1
    - Conclusion: remove phpstan/phpdoc-parser 0.4.2
    - Installation request for nunomaduro/phpinsights ^1.11 -> satisfiable by nunomaduro/phpinsights[v1.11.0, v1.11.1].
    - Conclusion: don't install phpstan/phpdoc-parser 0.4.2
    - nunomaduro/phpinsights v1.11.0 requires slevomat/coding-standard ^5.0 -> satisfiable by slevomat/coding-standard[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4].
    - slevomat/coding-standard 5.0.0 requires phpstan/phpdoc-parser ^0.3.1 -> satisfiable by phpstan/phpdoc-parser[0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5].
    - slevomat/coding-standard 5.0.1 requires phpstan/phpdoc-parser ^0.3.1 -> satisfiable by phpstan/phpdoc-parser[0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5].
    - slevomat/coding-standard 5.0.2 requires phpstan/phpdoc-parser ^0.3.1 -> satisfiable by phpstan/phpdoc-parser[0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5].
    - slevomat/coding-standard 5.0.3 requires phpstan/phpdoc-parser ^0.3.1 -> satisfiable by phpstan/phpdoc-parser[0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5].
    - slevomat/coding-standard 5.0.4 requires phpstan/phpdoc-parser ^0.3.1 -> satisfiable by phpstan/phpdoc-parser[0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5].
    - Can only install one of: phpstan/phpdoc-parser[0.3.1, 0.4.2].
    - Can only install one of: phpstan/phpdoc-parser[0.3.2, 0.4.2].
    - Can only install one of: phpstan/phpdoc-parser[0.3.3, 0.4.2].
    - Can only install one of: phpstan/phpdoc-parser[0.3.4, 0.4.2].
    - Can only install one of: phpstan/phpdoc-parser[0.3.5, 0.4.2].
    - Installation request for phpstan/phpdoc-parser (locked at 0.4.2) -> satisfiable by phpstan/phpdoc-parser[0.4.2].
```

The problem is that `slevomat/coding-standard:^5` requires `phpstan/phpdoc-parser:^0.3.1`.

But I have `Rector:^0.6` installed that requires `phpstan/phpdoc-parser:^0.4`.

So, until the version of `slevomat/coding-standard` is fixed on `0.3`, for me it is not possible to install both Rector and PHPInsights together.

The solution is to upgrade `slevomat/coding-standard` to version `^6` that uses `phpstan/phpdoc-parser:0.3.5 - 0.4.2`, so bein compatible with version constraints of Rector.

Unfortunately this is the first time I try to use PHPInsights, so I don't know which impact does it have to upgrade the version of `slevomat/coding-standards`.

This issue may be related to #340 .

**Comment by olivernybroe** [comment] 2020-01-17 10:11
In PR #342 We are working on adding support for slevomat version 6. 

In the meantime you can install it with the alternative solution given in the [docs](https://phpinsights.com/get-started.html#avoid-composer-conflicts).

**Comment by olivernybroe** [comment] 2020-01-17 10:13
I'll close this, as to be it seems to be a duplicate of #340, but thanks for raising the issue. 😄

**Closed by olivernybroe** 2020-01-17 10:13 UTC
