### ISSUE TITLE
Undefined offset: 0 | Fatal error: Uncaught TypeError: Argument 2 passed to SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatementPointers() must be of the type int, null given

### ISSUE THREAD

**Issue by filipac** [nunomaduro/phpinsights#59] opened 2019-05-15 12:11 UTC
Tried to run it on a Laravel app. Got this fatal error:

```
 605/910 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░]  66%PHP Notice:  Undefined offset: 0 in /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 147

Notice: Undefined offset: 0 in /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 147
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatementPointers() must be of the type int, null given, called in /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 149 and defined in /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php:193
Stack trace:
#0 /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php(149): SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatementPointers(Object(NunoMaduro\PhpInsights\Domain\File), NULL)
#1 /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php(111): SlevomatCodingStandard\Helpers\UseStatementHelper::getFileUseStatements(Object(NunoMaduro\PhpInsights\Domain\File))
#2 /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/PHP/OptimizedFunctions in /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 193

Fatal error: Uncaught TypeError: Argument 2 passed to SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatementPointers() must be of the type int, null given, called in /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 149 and defined in /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php:193
Stack trace:
#0 /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php(149): SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatementPointers(Object(NunoMaduro\PhpInsights\Domain\File), NULL)
#1 /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php(111): SlevomatCodingStandard\Helpers\UseStatementHelper::getFileUseStatements(Object(NunoMaduro\PhpInsights\Domain\File))
#2 /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/PHP/OptimizedFunctions in /Users/filipac/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 193
```

**Comment by liepumartins** [comment] 2019-05-17 13:37
Same issue. When running with verbose `-v` option I see that problem happens when tool hits certain `layout.blade.php` file.

**Comment by acurrieclark** [comment] 2019-05-19 20:15
I had a look through the `slevomat/coding-standard` package code, and this appears to be to do with php files which do not contain a full opening tag `<?php`.

I ran insights and found it failed on a template file of mine which contained a short `<?=` tag, but no full tag, and it failed with this error. I then added a full tag at the start of the file and then closed it immediately (an empty php block) and insights then failed with the same error on the next template it found.

**Comment by liepumartins** [comment] 2019-05-20 07:02
Yes, short tag is likely explanation.
In my case template contained some legacy spaghetti code such as:
`<?=(preg_match(PRIVILEGES['something'],$user['privileges'])?'<a href="..">aa</a>':'')?>`

Does this tool understand .blade.php files anyway? I could not get my head around if there is a way to exclude some file name patterns / directories. If not, there should be.

**Comment by nunomaduro** [comment] 2019-05-20 07:04
The folder `resources` is ignored on the Laravel preset, so your blade views should be ignored. No?

**Comment by liepumartins** [comment] 2019-05-20 07:20
Oh, sorry. My project is not Laravel, just blade template component, so the path is different.
I will have to learn how to create project settings/presets. :)

**Comment by nunomaduro** [comment] 2019-05-20 07:25
You just have to: `cp vendor/nunomaduro/phpinsights/stubs/config.php phpinsights.php`, than add the blade folder to the `exclude` key.

**Comment by nunomaduro** [comment] 2019-05-20 07:26
Actually, we should exclude all `*.blade.php` extensions. Can someone do a pull request on this? Here is the file: https://github.com/nunomaduro/phpinsights/blob/master/src/Infrastructure/Repositories/LocalFilesRepository.php

Don't forget to add tests on this.

**Comment by TheFrankman** [comment] 2019-06-12 09:41
For me it was jquery.repeater in node_modules. Luckily I don't really need it so just removed it.

**Comment by olivernybroe** [comment] 2019-06-12 11:06
@TheFrankman Hmm that's weird, we should be ignoring `node_modules`.

**Comment by TheFrankman** [comment] 2019-06-12 11:08
@olivernybroe I wouldn't concern yourself too much with it, It might be down to a theme that we are importing, it's a rather unusual laravel installation.

**Comment by nunomaduro** [comment] 2019-08-18 21:37
This issue has been fixed on the version `v1.8.1`.

**Closed by nunomaduro** 2019-08-18 21:37 UTC
Labels: bug, help wanted

**Comment by jadamec** [comment] 2019-08-19 05:36
```
λ php artisan insights
?[2K 53/65 [======================>-----]  81%
  ?[41;1m Symfony\Component\Debug\Exception\FatalThrowableError ?[49;22m : ?[33mArgument 1 passed to NunoMaduro\PhpInsights\Doma
in\File::resolveFullyQualifiedCode() must be of the type string, int given, called in C:\Users\jadam\bsgup\vendor\nunomaduro\php
insights\src\Domain\File.php on line 191?[39m

  at ?[32mC:\Users\jadam\bsgup\vendor\nunomaduro\phpinsights\src\Domain\File.php?[39m:?[32m222?[39m
    218|      * @param  string  $sniffClassOrCode
    219|      *
    220|      * @return string
    221|      */
  > 222|     private function resolveFullyQualifiedCode(string $sniffClassOrCode): string
    223|     {
    224|         if (class_exists($sniffClassOrCode)) {
    225|             return $sniffClassOrCode;
    226|         }

  ?[33mException trace:?[39m

  ?[36m1   ?[39m?[33mNunoMaduro\PhpInsights\Domain\File::resolveFullyQualifiedCode()?[39m
      ?[32mC:\Users\jadam\bsgup\vendor\nunomaduro\phpinsights\src\Domain\File.php?[39m:?[32m191?[39m

  ?[36m2   ?[39m?[33mNunoMaduro\PhpInsights\Domain\File::addMessage("Unparsable php code: syntax error or wrong phpdocs.", [])?[
39m
      ?[32mC:\Users\jadam\bsgup\vendor\squizlabs\php_codesniffer\src\Files\File.php?[39m:?[32m663?[39m

  ?[32mPlease use the argument ?[39m?[31m-v?[39m?[32m to see more details.?[39m
```

**Comment by michaeldyrynda** [comment] 2019-08-20 05:57
^ I hit the same error as @jadamec after updating to 1.8.1

**Comment by nunomaduro** [comment] 2019-08-20 14:46
@jadamec @michaeldyrynda Can you try again with `v1.9.0`?

**Comment by jadamec** [comment] 2019-08-20 14:58
> @jadamec @michaeldyrynda Can you try again with `v1.9.0`?

Works now, great! Thank you.

**Comment by michaeldyrynda** [comment] 2019-08-21 04:41
I did get a notice with 1.9, but it finished running.

**Comment by olivernybroe** [comment] 2019-08-21 07:12
@michaeldyrynda Could you share the notice, having some difficulties reproducing it.

**Comment by michaeldyrynda** [comment] 2019-08-21 10:12
`PHP Notice:  Undefined offset: 0 in /Users/mdyrynda/code/crm/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 147`

**Comment by olivernybroe** [comment] 2019-08-21 11:31
@michaeldyrynda Thanks. Found the cause.
PR #253 should silence the php messages
