### ISSUE TITLE
Resolve dependency - psr/simple-cache v1.0 - lara 9.x

### ISSUE THREAD

**Issue by peterfliszar** [nunomaduro/phpinsights#573] opened 2022-03-23 14:03 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 2.2.x

With Laravel 9.x installation, there is a conflict in dependencies.
- laravel require: "psr/simple-cache": "^1.0|^2.0|^3.0",
- phpinsights: "psr/simple-cache": "^1.0"

There is a workaround: locking all other packages to v1.0, it works fine, but this is only a workaround, not a permanent solution. I will test this.

Please resolve this conflict, if it is possible.

--

composer message:

Problem 1
    - Root composer.json requires nunomaduro/phpinsights ^2.2 -> satisfiable by nunomaduro/phpinsights[v2.2.0].
    - nunomaduro/phpinsights v2.2.0 requires psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require nunomaduro/phpinsights:*" to figure out if any version is installable, or "composer require nunomaduro/phpinsights:^2.1" if you know which you need.

**Comment by AyoobMH** [comment] 2022-03-27 15:06
I believe this is a duplicate of #522

**Comment by Krato** [comment] 2022-04-12 15:49
Yes. But, how to resolve?

**Comment by webard** [comment] 2022-04-16 20:38
Look at usage https://github.com/nunomaduro/phpinsights/search?q=simplecache and make PR with newer version in composer.json, checking if everything works fine.

**Comment by cmgmyr** [comment] 2022-05-27 14:46
Fixed in #580

**Closed by cmgmyr** 2022-05-27 14:46 UTC
