### ISSUE TITLE
Error when using php artisan insights

### ISSUE THREAD

**Issue by brunocfalcao** [nunomaduro/phpinsights#47] opened 2019-05-14 11:51 UTC
Hi Nuno,

Followed the instructions for the Laravel application, but somehow it gives this error when I run the artisan command:

![image](https://user-images.githubusercontent.com/34269950/57695716-45f9bf00-764f-11e9-9501-2a9b9146239b.png)

Thanks

**Comment by nunomaduro** [comment] 2019-05-14 11:54
Do you have a `composer.json` within your larapush folder?

**Comment by nunomaduro** [comment] 2019-05-14 11:55
Can you fork and try to bug fix this? I don't have a windows machine.

**Comment by antoniogarcia78** [comment] 2019-05-14 12:03
Same error.

**Comment by nunomaduro** [comment] 2019-05-14 12:07
@brunocfalcao @antoniogarcia78 Can you replace the `nunomaduro\phpinsights\src\Application\Console\Commands\AnalyseCommand.php:105` by:

```
        if ($directory[0] !== DIRECTORY_SEPARATOR && preg_match('~\A[A-Z]:(?![^/\\\\])~i', $directory) === 0) {
            $directory = (string) getcwd() . DIRECTORY_SEPARATOR . $directory;
        }
```

And check if it works?

**Comment by nunomaduro** [comment] 2019-05-14 12:16
Fixed on the version `v1.0.2`. https://github.com/nunomaduro/phpinsights/commit/8bae26f096f6f9e39e3dc2e6c03ec4acb4e3f802.

Please make sure you perform: `composer update nunomaduro/phpinsights` to get the latest version.

**Closed by nunomaduro** 2019-05-14 12:16 UTC
Labels: bug

**Comment by antoniogarcia78** [comment] 2019-05-14 12:43
You are fast. I try a fast fix using the constant PHP_OS. The problem is compare the first character with the DIRECTORY_SEPARATOR. 
If i use composer update i dont update more that 1.0.1

**Comment by nunomaduro** [comment] 2019-05-14 12:44
@antoniogarcia78 Try again. Takes some time.
