### ISSUE TITLE
Readonly Class Side Effects Issue (PHP 8.2)

### ISSUE THREAD

**Issue by ian-homeviews** [nunomaduro/phpinsights#637] opened 2023-03-28 15:54 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 2.8.0

If you have a class like this:

```php
readonly class FetchFiltersAction
 {
     public function __construct(
         private FilterOptionsRepository $filterOptionsRepository
     ) {
     }

     public function handle(FilterCollection $appliedFilters): FilterOptions
     {
         return $this->filterOptionsRepository->getFilterOptions($appliedFilters);
     }
 }
```

Then the following failure is shown:
* [Side effects] A file should declare new symbols (classes, functions, constants, etc.) and cause no other side effects, or it should execute logic with side effects, but should not do both. The first symbol is defined on line 11 and the first side effect is on line 11.

_(In this case line 11 references the first line in the code snippet above.)_

I believe this might be a php 8.2 issue as readonly classes were only recently introduced.

Thanks :)

**Comment by cmgmyr** [comment] 2023-09-28 02:39
This has been merged. I'm going to leave the change untagged in `master` for a few days so others can ensure everything is working as intended

**Closed by cmgmyr** 2023-09-28 02:39 UTC
